### ISSUE TITLE
No config or log created when runninng the bot on windows

### ISSUE THREAD

**Issue by helpfulBrother** [HydroProtocol/liquidation_bot#2]
Using,

`docker run -it --rm -v ./workingDir --name=auctionBidder hydroprotocolio/liquidation_bot:latest /bin/main`

The bot runs and connects, but I don't see any logs or config file created, so the bot asks for params every time?

**Comment by davidqhr** [comment]
Please try to mount a dir on `/workingDir`. I test this command in windows and it works. `docker run -it --rm -v F:\tmp:/workingDir --name=auctionBidder hydroprotocolio/liquidation_bot:latest /bin/main`

**Comment by helpfulBrother** [comment]
This worked perfectly thanks!
