### ISSUE TITLE
Will the ETH-DAI MARKETS param represent SAI post upgrade or DAI?

### ISSUE THREAD

**Issue by helpfulBrother** [HydroProtocol/liquidation_bot#3]
If SAI can the image please be updated to use the value SAI?

**Comment by helpfulBrother** [comment]
I had a look at the code and it appears to query ddex to translate the MARKET param.

So I'm guessing post upgrade ETH-SAI can be used for SAI and ETH-DAI for DAI?

**Comment by radar-bear** [comment]
Hi! We updated the token symbol from DAI to SAI. And will add Multi Collateral DAI (the new DAI) to market later.

Use SAI if you want to bid auction on old DAI market.
